site_name: Veille Tech
theme:
  name: material
  features:
    - navigation.footer
    - content.code.copy
nav:
  - Accueil: index.md
  - Archives: archives.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
extra_css:
  - styles/extra.css   # <-- point vers docs/styles/extra.css