name: Build & Deploy Veille

on:
  push:
    branches: [ main ]
  schedule:
    # Tous les lundis 06:00 UTC (08:00 Paris en hiver)
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs-material

      - name: Build weekly exports (crawl + IA + site content)
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}   # si tu utilises la notif
        run: |
          python veille_tech.py --config config.yaml
          python analyze_llm.py --config config.yaml
          python build_site.py

      - name: Setup git identity (gh-deploy push)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages (gh-pages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force --remote-branch gh-pages